### ISSUE TITLE
MacOSX M1 installation failure 

### ISSUE THREAD

**Issue by lucatoldo** [blazerye/DrugAssist#1]
Dear Authors,
on a MacOSX M1 running Sonoma, I did the following:
```
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh
git clone https://github.com/blazerye/DrugAssist.git\ncd DrugAssist
cd DrugAssist
conda create -n drugassist python=3.8 -y
conda activate drugassist
pip install -r requirements.txt
```
The last step failed due to missing packages:
"packaging"
"torch".

After manually pip installing them, 
sh run_sft_lora.sh failed due to missing packages:
- datasets
- transformers
- peft
- deepspeed

Unfortunately the latter could not be installed due to dependency with a non available package (cpuinfo).
Would be great if you could fix.

**Comment by blazerye** [comment]
Our model is trained on a Linux server with 8 NVIDIA Tesla A100-SXM4-40GB GPUs, and we strongly recommend using a server with NVIDIA GPUs for training, as training on Mac may be very slow. If you do need to train on Mac, please remove the `vllm` and `flash-attn` packages from the `requirements.txt` file, while keeping the other packages and their corresponding versions unchanged.
