### ISSUE TITLE
Issue in code

### ISSUE THREAD

**Issue by AKANKSHASINGH233** [blazerye/DrugAssist#2]
i am not able to install-flash-attn kindly share entire requirement file.

**Comment by AKANKSHASINGH233** [comment]
i was trying with python 3.8

**Comment by ajaymur91** [comment]
I had a lot of trouble installing as well. The following worked for me. Hope this helps
# nvidia-smi
# NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0 

mamba create -n drugassist4 python=3.8 pip cudatoolkit=11.7 cudatoolkit-dev=11.7 -c conda-forge -y
conda activate drugassist4
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
pip install packaging
pip install -r requirements.txt --no-build-isolation

**Comment by blazerye** [comment]
There is no problem using python 3.8 environment. We’ve received feedback regarding dependency issues in certain situations where package requirements cannot be satisfied. We’ve updated requirements.txt, and the change is:
vllm 0.1.3 -> 0.1.4, you can try again with it. Additionally, you can also try the solution provided by ajaymur91.

**Comment by mengtinghuang** [comment]
> 我无法安装-flash-attn，请共享整个需求文件。

I faced the same problem, have you solved it?

**Comment by mengtinghuang** [comment]
> i am not able to install-flash-attn kindly share entire requirement file.

I faced the same problem, have you solved it?

**Comment by lkffffffff** [comment]
> i am not able to install-flash-attn kindly share entire requirement file.

Me too. Have you solved it?

**Comment by lkffffffff** [comment]
> I had a lot of trouble installing as well. The following worked for me. Hope this helps
> 
> # nvidia-smi
> # NVIDIA-SMI 525.147.05 Driver Version: 525.147.05 CUDA Version: 12.0
> mamba create -n drugassist4 python=3.8 pip cudatoolkit=11.7 cudatoolkit-dev=11.7 -c conda-forge -y conda activate drugassist4 pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pip install packaging pip install -r requirements.txt --no-build-isolation

I still can't install flash-attn.

**Comment by dalecai666** [comment]
Regarding the issue of being unable to install the flash-attn package, we suggest referring to the official installation tutorial (https://github.com/Dao-AILab/flash-attention). Before installation, please check your local environment against the tutorial, such as hardware conditions, CUDA version, PyTorch version, and GCC version to see if they meet the requirements. We recommend downloading the installation package that is compatible with your environment from https://github.com/Dao-AILab/flash-attention/releases. If you still cannot install successfully, you can check whether there are solutions to similar problems in https://github.com/Dao-AILab/flash-attention/issues. If you are willing to share more details about your local environment and error messages here, we'd like to provide help.
