### ISSUE TITLE
Release of test molecules

### ISSUE THREAD

**Issue by ZHymLumine** [blazerye/DrugAssist#3]
Thank you for your impactful research shared in your recent paper. Your work is incredibly inspiring to the community.

Could you please consider making the 500 molecules from the ZINC dataset, which you used as a test set in your experiments, publicly available? Access to these molecules would greatly assist in replicating and extending your valuable findings.

Thank you for considering this request.

**Comment by blazerye** [comment]
Thank you for your interest in our work. I have uploaded the test set, and you can access it here: [https://huggingface.co/datasets/blazerye/MolOpt-Instructions/blob/main/test_500.txt](https://huggingface.co/datasets/blazerye/MolOpt-Instructions/blob/main/test_500.txt)

**Comment by ZHymLumine** [comment]
Thank you very much for sharing your work and the dataset! I have successfully accessed and downloaded the test set file. Your contribution is greatly valuable to our research.

If possible, I would like to inquire whether you could also provide the script for model evaluation? It would further assist us in understanding and applying your model, especially in terms of performance comparison and further research. Thank you again for your support and efforts!

**Comment by dalecai666** [comment]
We sincerely apologize for not following up on your needs in a timely manner. Our evaluation process follows the workflow proposed by ChatDrug (https://github.com/chao1224/ChatDrug). We have now updated the relevant scripts and their usage methods at https://github.com/blazerye/DrugAssist/tree/main/evaluate.
